/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.DashboardData;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DashboardDataControllerApi
 */
@Ignore
public class DashboardDataControllerApiTest {

    private final DashboardDataControllerApi api = new DashboardDataControllerApi();

    
    /**
     * getDashboardData
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDashboardDataUsingGETTest() throws ApiException {
        DashboardData response = api.getDashboardDataUsingGET();

        // TODO: test validations
    }
    
}
