/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param lat 
 * @param lon 
 * @param type 
 */
data class CarsharingData (
    val id: kotlin.String,
    val lat: kotlin.Float,
    val lon: kotlin.Float,
    val type: CarsharingData.Type
) {

    /**
    * 
    * Values: wESHARE,dRIVENOW,cAR2GO,jUMP
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "WESHARE") wESHARE("WESHARE"),
    
        @Json(name = "DRIVENOW") dRIVENOW("DRIVENOW"),
    
        @Json(name = "CAR2GO") cAR2GO("CAR2GO"),
    
        @Json(name = "JUMP") jUMP("JUMP");
    
    }

}

