/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.CarsharingData
import org.openapitools.client.models.FlightData
import org.openapitools.client.models.TrainData
import org.openapitools.client.models.WeatherData

/**
 * 
 * @param airport 
 * @param carsharingData 
 * @param trainData 
 * @param weatherData 
 */
data class DashboardData (
    val airport: FlightData,
    val carsharingData: kotlin.Array<CarsharingData>,
    val trainData: kotlin.Array<TrainData>,
    val weatherData: WeatherData? = null
) {

}

