/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.FlightDto
import org.openapitools.client.models.GoToInformation

/**
 * 
 * @param departures 
 * @param goToInformation 
 */
data class FlightData (
    val departures: kotlin.Array<FlightDto>,
    val goToInformation: GoToInformation
) {

}

