/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param counter 
 * @param departureTime 
 * @param destination 
 * @param flightNo 
 * @param gate 
 * @param status 
 * @param terminal 
 */
data class FlightDto (
    val counter: kotlin.String,
    val departureTime: java.time.LocalDateTime,
    val destination: kotlin.String,
    val flightNo: kotlin.String,
    val gate: kotlin.String,
    val status: kotlin.String,
    val terminal: kotlin.String
) {

}

