/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.GoToInformation
import org.openapitools.client.models.TripDto

/**
 * 
 * @param goToInformation 
 * @param station 
 * @param trips 
 */
data class TrainData (
    val goToInformation: GoToInformation,
    val station: kotlin.String,
    val trips: kotlin.Array<TripDto>
) {

}

