/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


/**
 * 
 * @param cancelled 
 * @param delay 
 * @param departureTime 
 * @param direction 
 * @param directionToDisplay 
 * @param platform 
 * @param trainIdentifier 
 * @param vehicleType 
 * @param via 
 * @param viaToDisplay 
 */
data class TripDto (
    val cancelled: kotlin.Boolean,
    val departureTime: java.time.LocalDateTime,
    val direction: kotlin.String,
    val directionToDisplay: kotlin.String,
    val trainIdentifier: kotlin.String,
    val vehicleType: kotlin.String,
    val via: kotlin.Array<kotlin.String>,
    val delay: kotlin.Int? = null,
    val platform: kotlin.String? = null,
    val viaToDisplay: kotlin.String? = null
) {

}

