/**
* Api Documentation
* Api Documentation
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param temperature 
 * @param weatherMainDescription 
 * @param willRainToday 
 */
data class WeatherData (
    val temperature: kotlin.Int,
    val weatherMainDescription: WeatherData.WeatherMainDescription,
    val willRainToday: kotlin.Boolean? = null
) {

    /**
    * 
    * Values: cLEARSKY,fEWCLOUDS,sCATTEREDCLOUDS,bROKENCLOUDS,sHOWERRAIN,rAIN,tHUNDERSTORM,sNOW,mIST
    */
    enum class WeatherMainDescription(val value: kotlin.String){
    
        @Json(name = "CLEAR_SKY") cLEARSKY("CLEAR_SKY"),
    
        @Json(name = "FEW_CLOUDS") fEWCLOUDS("FEW_CLOUDS"),
    
        @Json(name = "SCATTERED_CLOUDS") sCATTEREDCLOUDS("SCATTERED_CLOUDS"),
    
        @Json(name = "BROKEN_CLOUDS") bROKENCLOUDS("BROKEN_CLOUDS"),
    
        @Json(name = "SHOWER_RAIN") sHOWERRAIN("SHOWER_RAIN"),
    
        @Json(name = "RAIN") rAIN("RAIN"),
    
        @Json(name = "THUNDERSTORM") tHUNDERSTORM("THUNDERSTORM"),
    
        @Json(name = "SNOW") sNOW("SNOW"),
    
        @Json(name = "MIST") mIST("MIST");
    
    }

}

