/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CarsharingData;
import org.openapitools.client.model.FlightData;
import org.openapitools.client.model.TrainData;
import org.openapitools.client.model.WeatherData;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DashboardData
 */
public class DashboardDataTest {
    private final DashboardData model = new DashboardData();

    /**
     * Model tests for DashboardData
     */
    @Test
    public void testDashboardData() {
        // TODO: test DashboardData
    }

    /**
     * Test the property 'airport'
     */
    @Test
    public void airportTest() {
        // TODO: test airport
    }

    /**
     * Test the property 'carsharingData'
     */
    @Test
    public void carsharingDataTest() {
        // TODO: test carsharingData
    }

    /**
     * Test the property 'trainData'
     */
    @Test
    public void trainDataTest() {
        // TODO: test trainData
    }

    /**
     * Test the property 'weatherData'
     */
    @Test
    public void weatherDataTest() {
        // TODO: test weatherData
    }

}
