/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.FlightDto;
import org.openapitools.client.model.GoToInformation;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FlightData
 */
public class FlightDataTest {
    private final FlightData model = new FlightData();

    /**
     * Model tests for FlightData
     */
    @Test
    public void testFlightData() {
        // TODO: test FlightData
    }

    /**
     * Test the property 'departures'
     */
    @Test
    public void departuresTest() {
        // TODO: test departures
    }

    /**
     * Test the property 'goToInformation'
     */
    @Test
    public void goToInformationTest() {
        // TODO: test goToInformation
    }

}
