/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GoToDetail;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GoToInformation
 */
public class GoToInformationTest {
    private final GoToInformation model = new GoToInformation();

    /**
     * Model tests for GoToInformation
     */
    @Test
    public void testGoToInformation() {
        // TODO: test GoToInformation
    }

    /**
     * Test the property 'byBike'
     */
    @Test
    public void byBikeTest() {
        // TODO: test byBike
    }

    /**
     * Test the property 'byLocalTransport'
     */
    @Test
    public void byLocalTransportTest() {
        // TODO: test byLocalTransport
    }

    /**
     * Test the property 'byTaxi'
     */
    @Test
    public void byTaxiTest() {
        // TODO: test byTaxi
    }

    /**
     * Test the property 'byWalk'
     */
    @Test
    public void byWalkTest() {
        // TODO: test byWalk
    }

}
