/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GoToInformation;
import org.openapitools.client.model.TripDto;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TrainData
 */
public class TrainDataTest {
    private final TrainData model = new TrainData();

    /**
     * Model tests for TrainData
     */
    @Test
    public void testTrainData() {
        // TODO: test TrainData
    }

    /**
     * Test the property 'goToInformation'
     */
    @Test
    public void goToInformationTest() {
        // TODO: test goToInformation
    }

    /**
     * Test the property 'station'
     */
    @Test
    public void stationTest() {
        // TODO: test station
    }

    /**
     * Test the property 'trips'
     */
    @Test
    public void tripsTest() {
        // TODO: test trips
    }

}
