/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TripDto
 */
public class TripDtoTest {
    private final TripDto model = new TripDto();

    /**
     * Model tests for TripDto
     */
    @Test
    public void testTripDto() {
        // TODO: test TripDto
    }

    /**
     * Test the property 'cancelled'
     */
    @Test
    public void cancelledTest() {
        // TODO: test cancelled
    }

    /**
     * Test the property 'delay'
     */
    @Test
    public void delayTest() {
        // TODO: test delay
    }

    /**
     * Test the property 'departureTime'
     */
    @Test
    public void departureTimeTest() {
        // TODO: test departureTime
    }

    /**
     * Test the property 'direction'
     */
    @Test
    public void directionTest() {
        // TODO: test direction
    }

    /**
     * Test the property 'directionToDisplay'
     */
    @Test
    public void directionToDisplayTest() {
        // TODO: test directionToDisplay
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'trainIdentifier'
     */
    @Test
    public void trainIdentifierTest() {
        // TODO: test trainIdentifier
    }

    /**
     * Test the property 'vehicleType'
     */
    @Test
    public void vehicleTypeTest() {
        // TODO: test vehicleType
    }

    /**
     * Test the property 'via'
     */
    @Test
    public void viaTest() {
        // TODO: test via
    }

    /**
     * Test the property 'viaToDisplay'
     */
    @Test
    public void viaToDisplayTest() {
        // TODO: test viaToDisplay
    }

}
