//
// DashboardDataControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class DashboardDataControllerAPI {
    /**
     getDashboardData
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getDashboardDataUsingGET(completion: @escaping ((_ data: DashboardData?,_ error: Error?) -> Void)) {
        getDashboardDataUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     getDashboardData
     - GET /api/dashboard-data
     - returns: RequestBuilder<DashboardData> 
     */
    open class func getDashboardDataUsingGETWithRequestBuilder() -> RequestBuilder<DashboardData> {
        let path = "/api/dashboard-data"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<DashboardData>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
