//
// DashboardData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DashboardData: Codable {

    public var airport: FlightData
    public var carsharingData: [CarsharingData]
    public var trainData: [TrainData]
    public var weatherData: WeatherData?

    public init(airport: FlightData, carsharingData: [CarsharingData], trainData: [TrainData], weatherData: WeatherData?) {
        self.airport = airport
        self.carsharingData = carsharingData
        self.trainData = trainData
        self.weatherData = weatherData
    }


}

