//
// FlightDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FlightDto: Codable {

    public var counter: String
    public var departureTime: Date
    public var destination: String
    public var flightNo: String
    public var gate: String
    public var status: String
    public var terminal: String

    public init(counter: String, departureTime: Date, destination: String, flightNo: String, gate: String, status: String, terminal: String) {
        self.counter = counter
        self.departureTime = departureTime
        self.destination = destination
        self.flightNo = flightNo
        self.gate = gate
        self.status = status
        self.terminal = terminal
    }


}

