//
// FlightData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct FlightData: Codable {

    public var departures: [FlightDto]
    public var goToInformation: GoToInformation

    public init(departures: [FlightDto], goToInformation: GoToInformation) {
        self.departures = departures
        self.goToInformation = goToInformation
    }


}

