//
// GoToInformation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct GoToInformation: Codable {

    public var byBike: GoToDetail?
    public var byLocalTransport: GoToDetail
    public var byTaxi: GoToDetail
    public var byWalk: GoToDetail?

    public init(byBike: GoToDetail?, byLocalTransport: GoToDetail, byTaxi: GoToDetail, byWalk: GoToDetail?) {
        self.byBike = byBike
        self.byLocalTransport = byLocalTransport
        self.byTaxi = byTaxi
        self.byWalk = byWalk
    }


}

