//
// GoToDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct GoToDetail: Codable {

    public var detail: String
    public var requiredTime: String

    public init(detail: String, requiredTime: String) {
        self.detail = detail
        self.requiredTime = requiredTime
    }


}

