//
// TrainData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TrainData: Codable {

    public var goToInformation: GoToInformation
    public var station: String
    public var trips: [TripDto]

    public init(goToInformation: GoToInformation, station: String, trips: [TripDto]) {
        self.goToInformation = goToInformation
        self.station = station
        self.trips = trips
    }


}

