//
// WeatherData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct WeatherData: Codable {

    public enum WeatherMainDescription: String, Codable {
        case clearSky = "CLEAR_SKY"
        case fewClouds = "FEW_CLOUDS"
        case scatteredClouds = "SCATTERED_CLOUDS"
        case brokenClouds = "BROKEN_CLOUDS"
        case showerRain = "SHOWER_RAIN"
        case rain = "RAIN"
        case thunderstorm = "THUNDERSTORM"
        case snow = "SNOW"
        case mist = "MIST"
    }
    public var temperature: Int
    public var weatherMainDescription: WeatherMainDescription
    public var willRainToday: Bool?

    public init(temperature: Int, weatherMainDescription: WeatherMainDescription, willRainToday: Bool?) {
        self.temperature = temperature
        self.weatherMainDescription = weatherMainDescription
        self.willRainToday = willRainToday
    }


}

