/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CarsharingData;
import org.openapitools.client.model.FlightData;
import org.openapitools.client.model.TrainData;
import org.openapitools.client.model.WeatherData;

/**
 * DashboardData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-03T10:14:12.734Z[GMT]")
public class DashboardData {
  public static final String SERIALIZED_NAME_AIRPORT = "airport";
  @SerializedName(SERIALIZED_NAME_AIRPORT)
  private FlightData airport = null;

  public static final String SERIALIZED_NAME_CARSHARING_DATA = "carsharingData";
  @SerializedName(SERIALIZED_NAME_CARSHARING_DATA)
  private List<CarsharingData> carsharingData = new ArrayList<CarsharingData>();

  public static final String SERIALIZED_NAME_TRAIN_DATA = "trainData";
  @SerializedName(SERIALIZED_NAME_TRAIN_DATA)
  private List<TrainData> trainData = new ArrayList<TrainData>();

  public static final String SERIALIZED_NAME_WEATHER_DATA = "weatherData";
  @SerializedName(SERIALIZED_NAME_WEATHER_DATA)
  private WeatherData weatherData = null;

  public DashboardData airport(FlightData airport) {
    this.airport = airport;
    return this;
  }

   /**
   * Get airport
   * @return airport
  **/
  @ApiModelProperty(required = true, value = "")
  public FlightData getAirport() {
    return airport;
  }

  public void setAirport(FlightData airport) {
    this.airport = airport;
  }

  public DashboardData carsharingData(List<CarsharingData> carsharingData) {
    this.carsharingData = carsharingData;
    return this;
  }

  public DashboardData addCarsharingDataItem(CarsharingData carsharingDataItem) {
    this.carsharingData.add(carsharingDataItem);
    return this;
  }

   /**
   * Get carsharingData
   * @return carsharingData
  **/
  @ApiModelProperty(required = true, value = "")
  public List<CarsharingData> getCarsharingData() {
    return carsharingData;
  }

  public void setCarsharingData(List<CarsharingData> carsharingData) {
    this.carsharingData = carsharingData;
  }

  public DashboardData trainData(List<TrainData> trainData) {
    this.trainData = trainData;
    return this;
  }

  public DashboardData addTrainDataItem(TrainData trainDataItem) {
    this.trainData.add(trainDataItem);
    return this;
  }

   /**
   * Get trainData
   * @return trainData
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TrainData> getTrainData() {
    return trainData;
  }

  public void setTrainData(List<TrainData> trainData) {
    this.trainData = trainData;
  }

  public DashboardData weatherData(WeatherData weatherData) {
    this.weatherData = weatherData;
    return this;
  }

   /**
   * Get weatherData
   * @return weatherData
  **/
  @ApiModelProperty(value = "")
  public WeatherData getWeatherData() {
    return weatherData;
  }

  public void setWeatherData(WeatherData weatherData) {
    this.weatherData = weatherData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardData dashboardData = (DashboardData) o;
    return Objects.equals(this.airport, dashboardData.airport) &&
        Objects.equals(this.carsharingData, dashboardData.carsharingData) &&
        Objects.equals(this.trainData, dashboardData.trainData) &&
        Objects.equals(this.weatherData, dashboardData.weatherData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airport, carsharingData, trainData, weatherData);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardData {\n");
    sb.append("    airport: ").append(toIndentedString(airport)).append("\n");
    sb.append("    carsharingData: ").append(toIndentedString(carsharingData)).append("\n");
    sb.append("    trainData: ").append(toIndentedString(trainData)).append("\n");
    sb.append("    weatherData: ").append(toIndentedString(weatherData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

