/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GoToDetail;

/**
 * GoToInformation
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-03T10:14:12.734Z[GMT]")
public class GoToInformation {
  public static final String SERIALIZED_NAME_BY_BIKE = "byBike";
  @SerializedName(SERIALIZED_NAME_BY_BIKE)
  private GoToDetail byBike = null;

  public static final String SERIALIZED_NAME_BY_LOCAL_TRANSPORT = "byLocalTransport";
  @SerializedName(SERIALIZED_NAME_BY_LOCAL_TRANSPORT)
  private GoToDetail byLocalTransport = null;

  public static final String SERIALIZED_NAME_BY_TAXI = "byTaxi";
  @SerializedName(SERIALIZED_NAME_BY_TAXI)
  private GoToDetail byTaxi = null;

  public static final String SERIALIZED_NAME_BY_WALK = "byWalk";
  @SerializedName(SERIALIZED_NAME_BY_WALK)
  private GoToDetail byWalk = null;

  public GoToInformation byBike(GoToDetail byBike) {
    this.byBike = byBike;
    return this;
  }

   /**
   * Get byBike
   * @return byBike
  **/
  @ApiModelProperty(value = "")
  public GoToDetail getByBike() {
    return byBike;
  }

  public void setByBike(GoToDetail byBike) {
    this.byBike = byBike;
  }

  public GoToInformation byLocalTransport(GoToDetail byLocalTransport) {
    this.byLocalTransport = byLocalTransport;
    return this;
  }

   /**
   * Get byLocalTransport
   * @return byLocalTransport
  **/
  @ApiModelProperty(required = true, value = "")
  public GoToDetail getByLocalTransport() {
    return byLocalTransport;
  }

  public void setByLocalTransport(GoToDetail byLocalTransport) {
    this.byLocalTransport = byLocalTransport;
  }

  public GoToInformation byTaxi(GoToDetail byTaxi) {
    this.byTaxi = byTaxi;
    return this;
  }

   /**
   * Get byTaxi
   * @return byTaxi
  **/
  @ApiModelProperty(required = true, value = "")
  public GoToDetail getByTaxi() {
    return byTaxi;
  }

  public void setByTaxi(GoToDetail byTaxi) {
    this.byTaxi = byTaxi;
  }

  public GoToInformation byWalk(GoToDetail byWalk) {
    this.byWalk = byWalk;
    return this;
  }

   /**
   * Get byWalk
   * @return byWalk
  **/
  @ApiModelProperty(value = "")
  public GoToDetail getByWalk() {
    return byWalk;
  }

  public void setByWalk(GoToDetail byWalk) {
    this.byWalk = byWalk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoToInformation goToInformation = (GoToInformation) o;
    return Objects.equals(this.byBike, goToInformation.byBike) &&
        Objects.equals(this.byLocalTransport, goToInformation.byLocalTransport) &&
        Objects.equals(this.byTaxi, goToInformation.byTaxi) &&
        Objects.equals(this.byWalk, goToInformation.byWalk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byBike, byLocalTransport, byTaxi, byWalk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoToInformation {\n");
    sb.append("    byBike: ").append(toIndentedString(byBike)).append("\n");
    sb.append("    byLocalTransport: ").append(toIndentedString(byLocalTransport)).append("\n");
    sb.append("    byTaxi: ").append(toIndentedString(byTaxi)).append("\n");
    sb.append("    byWalk: ").append(toIndentedString(byWalk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

