/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GoToDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-03T10:14:12.734Z[GMT]")
public class GoToDetail {
  public static final String SERIALIZED_NAME_DETAIL = "detail";
  @SerializedName(SERIALIZED_NAME_DETAIL)
  private String detail;

  public static final String SERIALIZED_NAME_REQUIRED_TIME = "requiredTime";
  @SerializedName(SERIALIZED_NAME_REQUIRED_TIME)
  private String requiredTime;

  public GoToDetail detail(String detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public GoToDetail requiredTime(String requiredTime) {
    this.requiredTime = requiredTime;
    return this;
  }

   /**
   * Get requiredTime
   * @return requiredTime
  **/
  @ApiModelProperty(required = true, value = "")
  public String getRequiredTime() {
    return requiredTime;
  }

  public void setRequiredTime(String requiredTime) {
    this.requiredTime = requiredTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoToDetail goToDetail = (GoToDetail) o;
    return Objects.equals(this.detail, goToDetail.detail) &&
        Objects.equals(this.requiredTime, goToDetail.requiredTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detail, requiredTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoToDetail {\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    requiredTime: ").append(toIndentedString(requiredTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

