/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GoToInformation;
import org.openapitools.client.model.TripDto;

/**
 * TrainData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-03T10:14:12.734Z[GMT]")
public class TrainData {
  public static final String SERIALIZED_NAME_GO_TO_INFORMATION = "goToInformation";
  @SerializedName(SERIALIZED_NAME_GO_TO_INFORMATION)
  private GoToInformation goToInformation = null;

  public static final String SERIALIZED_NAME_STATION = "station";
  @SerializedName(SERIALIZED_NAME_STATION)
  private String station;

  public static final String SERIALIZED_NAME_TRIPS = "trips";
  @SerializedName(SERIALIZED_NAME_TRIPS)
  private List<TripDto> trips = new ArrayList<TripDto>();

  public TrainData goToInformation(GoToInformation goToInformation) {
    this.goToInformation = goToInformation;
    return this;
  }

   /**
   * Get goToInformation
   * @return goToInformation
  **/
  @ApiModelProperty(required = true, value = "")
  public GoToInformation getGoToInformation() {
    return goToInformation;
  }

  public void setGoToInformation(GoToInformation goToInformation) {
    this.goToInformation = goToInformation;
  }

  public TrainData station(String station) {
    this.station = station;
    return this;
  }

   /**
   * Get station
   * @return station
  **/
  @ApiModelProperty(required = true, value = "")
  public String getStation() {
    return station;
  }

  public void setStation(String station) {
    this.station = station;
  }

  public TrainData trips(List<TripDto> trips) {
    this.trips = trips;
    return this;
  }

  public TrainData addTripsItem(TripDto tripsItem) {
    this.trips.add(tripsItem);
    return this;
  }

   /**
   * Get trips
   * @return trips
  **/
  @ApiModelProperty(required = true, value = "")
  public List<TripDto> getTrips() {
    return trips;
  }

  public void setTrips(List<TripDto> trips) {
    this.trips = trips;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainData trainData = (TrainData) o;
    return Objects.equals(this.goToInformation, trainData.goToInformation) &&
        Objects.equals(this.station, trainData.station) &&
        Objects.equals(this.trips, trainData.trips);
  }

  @Override
  public int hashCode() {
    return Objects.hash(goToInformation, station, trips);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainData {\n");
    sb.append("    goToInformation: ").append(toIndentedString(goToInformation)).append("\n");
    sb.append("    station: ").append(toIndentedString(station)).append("\n");
    sb.append("    trips: ").append(toIndentedString(trips)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

