/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * TripDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-05-03T10:14:12.734Z[GMT]")
public class TripDto {
  public static final String SERIALIZED_NAME_CANCELLED = "cancelled";
  @SerializedName(SERIALIZED_NAME_CANCELLED)
  private Boolean cancelled;

  public static final String SERIALIZED_NAME_DELAY = "delay";
  @SerializedName(SERIALIZED_NAME_DELAY)
  private Integer delay;

  public static final String SERIALIZED_NAME_DEPARTURE_TIME = "departureTime";
  @SerializedName(SERIALIZED_NAME_DEPARTURE_TIME)
  private OffsetDateTime departureTime;

  public static final String SERIALIZED_NAME_DIRECTION = "direction";
  @SerializedName(SERIALIZED_NAME_DIRECTION)
  private String direction;

  public static final String SERIALIZED_NAME_DIRECTION_TO_DISPLAY = "directionToDisplay";
  @SerializedName(SERIALIZED_NAME_DIRECTION_TO_DISPLAY)
  private String directionToDisplay;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  private String platform;

  public static final String SERIALIZED_NAME_TRAIN_IDENTIFIER = "trainIdentifier";
  @SerializedName(SERIALIZED_NAME_TRAIN_IDENTIFIER)
  private String trainIdentifier;

  public static final String SERIALIZED_NAME_VEHICLE_TYPE = "vehicleType";
  @SerializedName(SERIALIZED_NAME_VEHICLE_TYPE)
  private String vehicleType;

  public static final String SERIALIZED_NAME_VIA = "via";
  @SerializedName(SERIALIZED_NAME_VIA)
  private List<String> via = new ArrayList<String>();

  public static final String SERIALIZED_NAME_VIA_TO_DISPLAY = "viaToDisplay";
  @SerializedName(SERIALIZED_NAME_VIA_TO_DISPLAY)
  private String viaToDisplay;

  public TripDto cancelled(Boolean cancelled) {
    this.cancelled = cancelled;
    return this;
  }

   /**
   * Get cancelled
   * @return cancelled
  **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getCancelled() {
    return cancelled;
  }

  public void setCancelled(Boolean cancelled) {
    this.cancelled = cancelled;
  }

  public TripDto delay(Integer delay) {
    this.delay = delay;
    return this;
  }

   /**
   * Get delay
   * @return delay
  **/
  @ApiModelProperty(value = "")
  public Integer getDelay() {
    return delay;
  }

  public void setDelay(Integer delay) {
    this.delay = delay;
  }

  public TripDto departureTime(OffsetDateTime departureTime) {
    this.departureTime = departureTime;
    return this;
  }

   /**
   * Get departureTime
   * @return departureTime
  **/
  @ApiModelProperty(required = true, value = "")
  public OffsetDateTime getDepartureTime() {
    return departureTime;
  }

  public void setDepartureTime(OffsetDateTime departureTime) {
    this.departureTime = departureTime;
  }

  public TripDto direction(String direction) {
    this.direction = direction;
    return this;
  }

   /**
   * Get direction
   * @return direction
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDirection() {
    return direction;
  }

  public void setDirection(String direction) {
    this.direction = direction;
  }

  public TripDto directionToDisplay(String directionToDisplay) {
    this.directionToDisplay = directionToDisplay;
    return this;
  }

   /**
   * Get directionToDisplay
   * @return directionToDisplay
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDirectionToDisplay() {
    return directionToDisplay;
  }

  public void setDirectionToDisplay(String directionToDisplay) {
    this.directionToDisplay = directionToDisplay;
  }

  public TripDto platform(String platform) {
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @ApiModelProperty(value = "")
  public String getPlatform() {
    return platform;
  }

  public void setPlatform(String platform) {
    this.platform = platform;
  }

  public TripDto trainIdentifier(String trainIdentifier) {
    this.trainIdentifier = trainIdentifier;
    return this;
  }

   /**
   * Get trainIdentifier
   * @return trainIdentifier
  **/
  @ApiModelProperty(required = true, value = "")
  public String getTrainIdentifier() {
    return trainIdentifier;
  }

  public void setTrainIdentifier(String trainIdentifier) {
    this.trainIdentifier = trainIdentifier;
  }

  public TripDto vehicleType(String vehicleType) {
    this.vehicleType = vehicleType;
    return this;
  }

   /**
   * Get vehicleType
   * @return vehicleType
  **/
  @ApiModelProperty(required = true, value = "")
  public String getVehicleType() {
    return vehicleType;
  }

  public void setVehicleType(String vehicleType) {
    this.vehicleType = vehicleType;
  }

  public TripDto via(List<String> via) {
    this.via = via;
    return this;
  }

  public TripDto addViaItem(String viaItem) {
    this.via.add(viaItem);
    return this;
  }

   /**
   * Get via
   * @return via
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getVia() {
    return via;
  }

  public void setVia(List<String> via) {
    this.via = via;
  }

  public TripDto viaToDisplay(String viaToDisplay) {
    this.viaToDisplay = viaToDisplay;
    return this;
  }

   /**
   * Get viaToDisplay
   * @return viaToDisplay
  **/
  @ApiModelProperty(value = "")
  public String getViaToDisplay() {
    return viaToDisplay;
  }

  public void setViaToDisplay(String viaToDisplay) {
    this.viaToDisplay = viaToDisplay;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TripDto tripDto = (TripDto) o;
    return Objects.equals(this.cancelled, tripDto.cancelled) &&
        Objects.equals(this.delay, tripDto.delay) &&
        Objects.equals(this.departureTime, tripDto.departureTime) &&
        Objects.equals(this.direction, tripDto.direction) &&
        Objects.equals(this.directionToDisplay, tripDto.directionToDisplay) &&
        Objects.equals(this.platform, tripDto.platform) &&
        Objects.equals(this.trainIdentifier, tripDto.trainIdentifier) &&
        Objects.equals(this.vehicleType, tripDto.vehicleType) &&
        Objects.equals(this.via, tripDto.via) &&
        Objects.equals(this.viaToDisplay, tripDto.viaToDisplay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cancelled, delay, departureTime, direction, directionToDisplay, platform, trainIdentifier, vehicleType, via, viaToDisplay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TripDto {\n");
    sb.append("    cancelled: ").append(toIndentedString(cancelled)).append("\n");
    sb.append("    delay: ").append(toIndentedString(delay)).append("\n");
    sb.append("    departureTime: ").append(toIndentedString(departureTime)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    directionToDisplay: ").append(toIndentedString(directionToDisplay)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    trainIdentifier: ").append(toIndentedString(trainIdentifier)).append("\n");
    sb.append("    vehicleType: ").append(toIndentedString(vehicleType)).append("\n");
    sb.append("    via: ").append(toIndentedString(via)).append("\n");
    sb.append("    viaToDisplay: ").append(toIndentedString(viaToDisplay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

